import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";

import {
  ReviewedDrink,
  Look,
  Taste,
  Linger,
} from "../public/static/interfaces";
import GimmeDrinks from "../public/static/hold.json";
import { defaultDrink } from "../components/statics";
import DrinkMain from "@/components/drink/singleDrink";

export default function DrinkPage() {
  const [singleDrink, setSingleDrink] = useState<ReviewedDrink>();
  const [look, setLook] = useState<Look>();
  const [taste, setTaste] = useState<Taste>();
  const [linger, setLinger] = useState<Linger>();

  const selectedDrink = async (id: string) => {
    var drink = defaultDrink;
    for (var i = 0; i < GimmeDrinks.length; i++) {
      if (GimmeDrinks[i]["drink"]["id"] === id) {
        drink = GimmeDrinks[i]["drink"] as ReviewedDrink;
        break;
      }
    }
    setSingleDrink(drink);
    setLook(drink.fullTasting.look);
    setTaste(drink.fullTasting.taste);
    setLinger(drink.fullTasting.linger);
  };

  const reqIDnull = useSearchParams().get("id");

  useEffect(() => {
    reqIDnull ? selectedDrink(reqIDnull) : selectedDrink("");
  }, [reqIDnull]);
  return (
    <>
      <Head>
        <title>Whiskey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-white flex flex-col h-screen">
        <header className="sticky z-50 top-0 inset-x-0 border-b border-gray-200 shadow-lg p-5 bg-[#0d1117] grid grid-cols-7">
          <div className="relative left-[7%] sm:left-[5%] xl:left-[3%] text-3xl col-span-6">
            {"DG \xa0 Whisk(e)y"}
          </div>
          <button
            className="rounded-2xl text-base sm:text-xl bg-gray-500 text-center cursor-pointer col-span-1"
            onClick={() => window.location.assign("./")}
          >
            Back
          </button>
        </header>
        <main className="flex-grow h-full bg-gradient-to-b from-black to-orange-400 bg-auto justify-center flex overflow-y-auto relative">
          <div className="">
            <DrinkMain />
          </div>
        </main>
      </div>
    </>
  );
}
